name: conan-fmilibrary CI Conan

# This workflow is triggered on pushes to the repository.
on: [push, workflow_dispatch]

env:
  CONAN_LOGIN_USERNAME_AIS: ${{ secrets.CONAN_LOGIN_USERNAME_AIS }}
  CONAN_PASSWORD_AIS: ${{ secrets.CONAN_PASSWORD_AIS }}
  CONAN_REVISIONS_ENABLED: 1
  CONAN_NON_INTERACTIVE: True

jobs:
  conan-on-linux:
    name: Conan
    runs-on: ${{ matrix.os }}
    env:
      CC: gcc-${{ matrix.compiler_version }}
      CXX: g++-${{ matrix.compiler_version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        build_type: [Debug, Release]
        compiler_version: [7, 9]
        compiler_libcxx: [libstdc++11]
        option_shared: ['True', 'False']
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          sudo pip3 install --upgrade setuptools pip
          sudo pip3 install conan
      - run: conan remote add ais https://ais.jfrog.io/artifactory/api/conan/ais-conan --force
      - run: conan create -s build_type=${{ matrix.build_type }} -s compiler.version=${{ matrix.compiler_version }} -s compiler.libcxx=${{ matrix.compiler_libcxx }} -o fmilibrary:shared=${{ matrix.option_shared }} . _/_
      - run: conan upload --all -c -r ais 'fmilibrary*'

  conan-on-windows:
    name: Conan
    runs-on: ${{ matrix.os }}
    env:
      CONAN_USER_HOME_SHORT: C:\c
      CONAN_USE_ALWAYS_SHORT_PATHS: 1
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022]
        build_type: [Debug, Release]
        option_shared: ['True', 'False']
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          pip3 install --upgrade setuptools pip
          pip3 install conan
      - run: conan remote add ais https://ais.jfrog.io/artifactory/api/conan/ais-conan --force
      - run: conan create -s build_type=${{ matrix.build_type }} -o fmilibrary:shared=${{ matrix.option_shared }} . _/_
      - run: conan upload --all -c -r ais 'fmilibrary*'
